services:
  core:
    build:
      context: ../
      dockerfile: ./docker/rootless/Dockerfile
      args:
        - BASE_IMAGE=ubuntu:22.04
        - PROJECT_NAME=${PROJECT_NAME:-pytorch-template}
        - PYTHON_VERSION=3.12.10
        - UV_VERSION=0.7.12
        - UV_TORCH_SOURCE=cpu
    tty: true
    restart: always
    shm_size: 16g
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_IP=0.0.0.0
      - JUPYTER_PORT=8888
      - JUPYTER_NOTEBOOK_DIR=/${PROJECT_NAME:-pytorch-template}
      - PROJECT_NAME=${PROJECT_NAME:-pytorch-template}
    volumes:
      - ../:/${PROJECT_NAME:-pytorch-template}
    ports:
      - 8888:8888
    command: /bin/bash

