services:
  pytorch-template:
    build:
      context: ../
      dockerfile: ./docker/rootless/Dockerfile
      args:
        - BASE_IMAGE=ubuntu:22.04
        - PROJECT_NAME=pytorch-template
        - PYTHON_VERSION=3.11.9
    tty: true
    restart: always
    shm_size: 16g
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_IP=0.0.0.0
      - JUPYTER_PORT=8888
      - JUPYTER_NOTEBOOK_DIR=/pytorch-template
      - PROJECT_NAME=pytorch-template
    volumes:
      - ../:/pytorch-template
    ports:
      - 8888:8888
    command: /bin/bash

